### ISSUE TITLE
webpack `stats.json` original filename?

### ISSUE THREAD

**Issue by iam4x** [webpack/url-loader#11]
Hey,

For my server side rendering, I would need to map the original filename/path to the generated one. To make `require(xxxx.png)` works in node.

Is there a way to achieve this easily?

**Comment by sokra** [comment]
`stats.modules[x].assets`

**Comment by iam4x** [comment]
@sokra 

Let's say I have this:

```
<img src={require('react-logo.png')} />
```

In my `stats.json` if I search for `react-logo` there's no results. I want to map the original filename to the generated one.

**Comment by sokra** [comment]
in `stats.modules` you have all modules in this format:

``` js
{
	id: 11,
	identifier: "(webpack)\\node_modules\\file-loader\\index.js!(webpack)\\test\\browsertest\\img\\image.png",
	name: "(webpack)/~/file-loader!./img/image.png",
	size: 81,
	cacheable: true,
	built: true,
	optional: false,
	prefetched: false,
	chunks: [0],
	assets: ["c31e9820c001c9c4a86bce33ce43b679.png"],
	issuer: "(webpack)\\test\\browsertest\\lib\\index.web.js",
	profile: {
		factory: 245,
		building: 121
	},
	failed: false,
	errors: 0,
	warnings: 0,
	reasons: [
		{
			moduleId: 0,
			moduleIdentifier: "(webpack)\\test\\browsertest\\lib\\index.web.js",
			module: "./lib/index.web.js",
			moduleName: "./lib/index.web.js",
			type: "cjs require",
			userRequest: "!file!../img/image.png",
			loc: "105: 3-36"
		}
	],
	source: 'module.exports = __webpack_public_path__ + "c31e9820c001c9c4a86bce33ce43b679.png"'
}
```

`assets: ["c31e9820c001c9c4a86bce33ce43b679.png"]`

**Comment by iam4x** [comment]
Thanks found it :+1:

**Comment by halt-hammerzeit** [comment]
FYI
https://github.com/halt-hammerzeit/webpack-isomorphic-tools

This module enables the thing you tried to implement (requiring images on server for example)
