### ISSUE TITLE
How to output a image file in css background-image to another folder?

### ISSUE THREAD

**Issue by hkongm** [webpack/url-loader#16]
The question likes https://github.com/webpack/file-loader/issues/32

It's seems no way to resolve this...

Thanks.

**Comment by qiankun007** [comment]
it is not a bug, you can add a query parameter `name=xxx` like this   
```
    {
                test: /\.(png|jpg)$/,
                loader: 'url-loader?limit=100000&name=./imgs/[hash].[ext]'
    }
``` 

see [loader-utils](https://github.com/webpack/loader-utils) source code

**Comment by hkongm** [comment]
thanks very much
