### ISSUE TITLE
Is "prefix" query parameter supported?

### ISSUE THREAD

**Issue by SukantGujar** [webpack/url-loader#22]
Quoting the doc -
> require("url?prefix=img/!./file.png");
>// => Parameters for the file-loader are valid too
>//    They are passed to the file-loader if used.

Outside of this example, I haven't found any mention of the "prefix" parameter either in file-loader, or in loader-utils code. Is this parameter valid!?

**Comment by Robin-front** [comment]
+1  prefix not working

**Comment by Robin-front** [comment]
I found the method

update the file-upload@0.9.0  

```sh
npm install --save-dev file-upload@0.9.0
```

then, webpack.config like this: use  `publicPath`  paramter

```js
{ 
        test: /\.(png|jpe?g|gif)$/,
        loader: 'url-loader?publicPath=http://www.img-cdn.com/&limit=8192&name=[name]-[hash].[ext]'
      }
```
It will add imgs prefix, only.

if you want to add prefix in all of css, js, imgs ; you can write `publicPath` in `output`

```js
output: {
    path: path.join(__dirname, 'dist'),
    publicPath: 'http://www.img-cdn.com/',
    filename: 'js/[name].[hash].js'
  },
```

**Comment by SukantGujar** [comment]
Thanks!

**Comment by nimojs** [comment]
Because based on `file-loader` so:

```js
{
    test: /\.(png|jpg|jpeg|gif)(\?v=\d+\.\d+\.\d+)?$/i,
    loader: 'url?name=__media/[path][name][hash].[ext]'
}
```
`name=__media/[path][name][hash].[ext]`

@d3viant0ne 

If don't support `prefix`, please delete documents related parts,thanks.
