### ISSUE TITLE
require path 

### ISSUE THREAD

**Issue by cuining** [webpack/url-loader#32]
hi,sometimes i use `require('./src/img/nobodyon.png')` in js,i want to change the path into a variable,
like `require(src)` ,but it doesn't work

**Comment by ezhlobo** [comment]
@cuining hi. It can help:

* [webpack context](https://webpack.github.io/docs/context.html), for dynamic requires
* [Similar issue on webpack repository](https://github.com/webpack/webpack/issues/118)

**Comment by cuining** [comment]
@ezhlobo Thanks
