### ISSUE TITLE
Opt out of `limit`

### ISSUE THREAD

**Issue by possibilities** [webpack/url-loader#8]
To opt out you have to include a silly large value. If you want this and suggest a name for the option I'll implement it, what do you think @sokra. Thanks either way! (;

**Comment by sokra** [comment]
Just don't pass limit...

**Comment by possibilities** [comment]
No limit defaults to 0. Instead I'm using limit=1 which is fine but I think
it's not uncommon that you want to file-load all of the urls found in css
in a project. no?

**Comment by sokra** [comment]
no limit or limit=0 mean only DataUrl and no file-loader.

**Comment by possibilities** [comment]
OH! I want to force file loader. I didn't realize I could use it directly and skip url loader all together! Thanks!
